### ISSUE TITLE
[ERROR] Too long extrusion prevented

### ISSUE THREAD

**Issue by codigoneo** [pinguinpfleger/ASWX1-FW-MOD#19]
### Bug Description

I was printing a keychain with filament color change and after changing the filament I hit continue. Then I got an error "too long extrusion prevented". The printer went crazy and beeped. I tried to continue printing several times but it can not. I tried changing the filament again, but it didn't solve the problem. Finally I tried to turn off the printer and recover the print, but it continued to print in the air (where the filament change was made).

### My Configurations

https://github.com/pinguinpfleger/ASWX1-FW-MOD/releases/tag/ASWX1-FW-MOD-v1.2 without changes
https://github.com/wgcv/RAWR-TFT-Firmware-Artillery3D/releases/tag/V28.0.2 without changes

### Steps to Reproduce

1. Print the gcode
2. Change filament
3. Resume print

**Expected behavior:** Print normally

**Actual behavior:** An error appears and does not print

#### Additional Information

* gcode file
[audiKeychain.zip](https://github.com/pinguinpfleger/ASWX1-FW-MOD/files/6759815/audiKeychain.zip)

**Comment by Bodengriller** [comment]
This will be related to your TFT firmware. I have printed your gcode file 3 times (third time with small change):
1. via Octoprint (M600 does not work)
2. via USB stick (M600 does not work either - here I manually selected "filament change" via TFT)
3. by Octoprint with a pause command instead of filament change (look at the code from line 12,580)
You can do this quite comfortable with the Cura plugin "Pause-At-Height".
[audiKeychain pause.zip](https://github.com/pinguinpfleger/ASWX1-FW-MOD/files/6760067/audiKeychain.pause.zip)

![IMG_20210704_162132](https://user-images.githubusercontent.com/50927649/124389305-caec3a80-dce6-11eb-8221-bbee61163c56.jpg)

I can't give you any further information about your TFT firmware. You have to open an issue with the TFT-FW-developer.


**My Configurations**
https://github.com/pinguinpfleger/ASWX1-FW-MOD/releases/tag/ASWX1-FW-MOD-v1.2 without changes
https://github.com/pinguinpfleger/ASWX1-TFTFW-MOD/releases/tag/ASWX1-TFTFW-MOD-v1.1 without changes
